Feature rationale1
razor-network/razor-go pull request #120
Opened 2021-08-11 08:12 UTC by Yashk767

resolve #108 
- Added address.json file.
- Fetched deployed addresses from json file.
- Added address.go file in utils folder for getter functions of deployed addresses.

2021-08-11 08:20 UTC, SkandaBhat commented
Rename PR title to something more meaningful and add "Fixes #<issue number>" instead of 'resolve'

2021-08-11 08:46 UTC, Yashk767 commented
I already ran go fmt over the files mentioned in build error, why is build still failing ?

2021-08-11 08:46 UTC, SkandaBhat requested changes

2021-08-11 08:46 UTC, SkandaBhat commented on utils/addresses.go
> +	addresses := core.AssignAddressesFromJSON()
Is it not possible to initialise addresses once and just return respective addresses in the getters?

2021-08-11 08:48 UTC, SkandaBhat requested changes

2021-08-11 08:48 UTC, SkandaBhat commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Read this from .razor/ and not ./

2021-08-11 08:48 UTC, SkandaBhat commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Check how config reading is implemented. Should be same

2021-08-11 08:59 UTC, Yashk767 commented on utils/addresses.go
> +	addresses := core.AssignAddressesFromJSON()
No, It is not possible if we want to get getters for each contract addresses.

2021-08-11 08:59 UTC, SkandaBhat commented on utils/addresses.go
> +	addresses := core.AssignAddressesFromJSON()
ok

2021-08-11 08:59 UTC, Yashk767 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Okay, will make the changes.

2021-08-11 09:25 UTC, Yashk767 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Do you mean should I move the file this to razor-go as it would be the root directory , and  even after that path would change to "./../addresses.json" so how can i use .razor/ . As .razor/ would be formed after building the node.

2021-08-11 09:35 UTC, ashish10677 commented
> I already ran go fmt over the files mentioned in build error, why is build still failing ?

Did you run `gofmt -w .` and `golangci-lint run` both on the entire repo?

2021-08-11 10:18 UTC, Yashk767 commented
> > I already ran go fmt over the files mentioned in build error, why is build still failing ?
> 
> Did you run `gofmt -w .` and `golangci-lint run` both on the entire repo?

I did run both over the updated files but not over the entire repo. I will entirely run it once and commit.

2021-08-11 10:35 UTC, SkandaBhat commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Hmm. @ashish10677 do you have an opinion on this?

2021-08-11 11:35 UTC, ashish10677 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
I guess we can move addresses.json to the **root of the project** and we can get the current working directory, then the path would be `currentWorkingDir/addresses.json`

2021-08-11 11:36 UTC, ashish10677 commented
@Yashk767 why is the build failing? Is your code compiling?
cc: @SkandaBhat

2021-08-11 11:51 UTC, Yashk767 commented
> @Yashk767 why is the build failing? Is your code compiling?
> cc: @SkandaBhat

Yes its compiling and I am also able to build the razor node successfully . Idk why the build is failing.

2021-08-11 13:50 UTC, SkandaBhat commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Works. @Yashk767 please implement accordingly

2021-08-11 13:54 UTC, SkandaBhat commented
circle ci is failing because you have not updated your branch with main branch. @Yashk767 

https://app.circleci.com/pipelines/github/razor-network/razor-go/34/workflows/5832934c-5ae7-4e6b-85a1-d73def5fe319/jobs/54

2021-08-11 14:36 UTC, Yashk767 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
I will move the addresses.json in root than path would be "./../addresses.json", as I can only get the working directory by os.Getwd() but I didn't find any utility method to get the project root directory. Should I follow with the described path ?

2021-08-11 14:53 UTC, ashish10677 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
Does this help in getting you the project root?
https://stackoverflow.com/questions/31873396/is-it-possible-to-get-the-current-root-of-package-structure-as-a-string-in-golan

2021-08-11 15:06 UTC, Yashk767 commented on core/constants.go
> +	data, err := ioutil.ReadFile("./addresses.json")
okay

2021-08-11 15:19 UTC, Yashk767 commented
How can I fix this error of restoring cache in build. @SkandaBhat 

https://app.circleci.com/pipelines/github/razor-network/razor-go/36/workflows/b85dd4a2-0a5b-4dc6-ac99-fb7696ff2ffc/jobs/56

2021-08-12 05:43 UTC, ashish10677 requested changes

2021-08-12 05:43 UTC, ashish10677 commented on cmd/job.go
> +		contractAddress := common.HexToAddress(assetManagerAddress)
Can't you directly call GetAssetManagerAddresss() without assigning it to another variable?
```
contractAddress := common.HexToAddress(utils.GetAssetManagerAddress())
```
I'm suggesting this because assetManagerAddress isn't used anywhere else in this file.

2021-08-12 05:43 UTC, ashish10677 commented on cmd/vote.go
> +			common.HexToAddress(blockManagerAddress),
Same thing here as well.

2021-08-12 05:43 UTC, ashish10677 commented on utils/contract-manager.go
> +	RAZORAddress := GetRAZORAddress()
In this file as well.

2021-08-12 05:50 UTC, Yashk767 commented on cmd/job.go
> +		contractAddress := common.HexToAddress(assetManagerAddress)
Okay , I will make the changes.

2021-08-12 05:54 UTC, SkandaBhat commented on cmd/job.go
> +		contractAddress := common.HexToAddress(assetManagerAddress)
+1

2021-08-12 08:02 UTC, SkandaBhat commented
@Yashk767 please have a separate destination for storing the addresses.json file. Ideally `<razor-go>/deployed_addresses/addresses.json`

2021-08-12 08:13 UTC, Yashk767 commented
> @Yashk767 please have a separate destination for storing the addresses.json file. Ideally `<razor-go>/deployed_addresses/addresses.json`

The new path to addresses.json from core/constants.go would be "./../deployed_addresses/addresses.json". As I need to mention this path in function AssignAddressesFromJSON() in order to parse, so should I follow this path ?

2021-08-12 11:09 UTC, ashish10677 commented
> > @Yashk767 please have a separate destination for storing the addresses.json file. Ideally `<razor-go>/deployed_addresses/addresses.json`
> 
> The new path to addresses.json from core/constants.go would be "./../deployed_addresses/addresses.json". As I need to mention this path in function AssignAddressesFromJSON() in order to parse, so should I follow this path ?

Yes you can follow that

2021-08-18 09:12 UTC, ashish10677 approved these changes

2021-08-19 07:52 UTC, merged