Propose only when iteration is less than last block in alt blocks when no. of proposed blocks == max alt blocks
razor-network/razor-go pull request #139
Opened 2021-08-18 13:25 UTC by Yashk767

fix #95

2021-08-24 11:32 UTC, SkandaBhat commented on cmd/propose.go
> +		log.Infof("Number of blocks proposed: %s, which is equal or greater than maximum alternative blocks allowed", numOfProposedBlocks)
What is Infof?

2021-08-24 11:45 UTC, ashish10677 commented on cmd/propose.go
> +		log.Infof("Number of blocks proposed: %s, which is equal or greater than maximum alternative blocks allowed", numOfProposedBlocks)
`Infof` is like `printf`, a statement that supports string formatting.

2021-08-24 11:54 UTC, ashish10677 requested changes

2021-08-24 11:54 UTC, ashish10677 commented on cmd/propose.go
> +	if numOfProposedBlocks.Cmp(maxAltBlocks) == 0 || numOfProposedBlocks.Cmp(maxAltBlocks) == 1 {
Can't you check for >= 0 directly? Instead of checking 2 conditions?

2021-08-24 11:54 UTC, ashish10677 commented on cmd/propose.go
> +		lastBlockIndex.Sub(numOfProposedBlocks, big.NewInt(1))
This and the above statement can be consolidated into one:
```
lastBlockIndex := big.NewInt(0).Sub(numOfProposedBlocks, big.NewInt(1))
```

2021-08-24 11:54 UTC, ashish10677 commented on cmd/propose.go
> +		if lastIteration.Cmp(big.NewInt(int64(iteration))) == -1 {
This is not wrong, but I feel, writing `<0` makes it easier to understand.

2021-08-24 12:02 UTC, Yashk767 commented on cmd/propose.go
> +	if numOfProposedBlocks.Cmp(maxAltBlocks) == 0 || numOfProposedBlocks.Cmp(maxAltBlocks) == 1 {
yes, I can do that.

2021-08-25 09:32 UTC, ashish10677 approved these changes

2021-08-30 07:20 UTC, merged