Feature password flag
razor-network/razor-go pull request #151
Opened 2021-08-20 11:30 UTC by Yashk767

fix #131 
- Added utility functions GetPasswordFromFile() and IsFlagPassed()
- Added a feature to read the password from file when password flag is provided with a path to file as its value.

2021-08-20 13:32 UTC, ashish10677 requested changes

2021-08-20 13:32 UTC, ashish10677 commented on cmd/create.go
> +	createCmd.Flags().StringVarP(&Password, "password", "", "", "password of the user")
Change description to "password file path to protect the keystore"

2021-08-20 13:32 UTC, ashish10677 commented on cmd/resetLock.go
> +		var password string
Can this whole block be converted to a function, and used as a one-line call to that function. This piece of code is being used a lot.

2021-08-20 14:05 UTC, Yashk767 commented on cmd/resetLock.go
> +		var password string
yes this could be converted. We can make a function with argument as flagset type, as we need cmd.Flags() to get the flags from the command.

2021-08-20 17:26 UTC, SkandaBhat commented
We need a warning if a user uses the --password flag.

2021-08-24 11:29 UTC, SkandaBhat commented on utils/password.go
> +			Label:     "Setting password from file at described path, are you sure?",
The point of fetching passwords from files is to prevent prompts in CI settings. 

We need to just print a warning if the flag is passed, not as for prompt.

2021-08-24 11:29 UTC, SkandaBhat approved these changes

2021-08-24 11:30 UTC, SkandaBhat requested changes
Please remove prompt.

2021-08-24 11:38 UTC, Yashk767 commented on utils/password.go
> +			Label:     "Setting password from file at described path, are you sure?",
Okay, I will change it.

2021-08-24 11:48 UTC, ashish10677 commented on utils/password.go
> +			Label:     "Setting password from file at described path, are you sure?",
@Yashk767 you can use `log.Warn` for sending out a warning.

2021-08-30 10:34 UTC, SkandaBhat commented
This Branch was force pushed. Please create a new PR and get it reviewed from @ashish10677. Closing this.

2021-08-30 10:34 UTC, closed without merging