Transact fractional RZRs
razor-network/razor-go pull request #180
Opened 2021-09-01 07:59 UTC by Yashk767

Closes #169

2021-09-01 17:46 UTC, ashish10677 requested changes

2021-09-01 17:46 UTC, ashish10677 commented on utils/math.go
> +	amountInWei := big.NewInt(1).Mul(amount, big.NewInt(0).Exp(big.NewInt(10), _power, nil))
Make this as `big.NewInt(1).Exp(big.NewInt(10), _power)`

2021-09-01 17:46 UTC, ashish10677 commented on utils/math_test.go
>  			want:          big.NewInt(1).Mul(big.NewInt(1000), big.NewInt(1e18)),
Write Test cases for all the new functions introduced in utils/math.go

2021-09-01 17:47 UTC, ashish10677 commented
Please link the issues to this PR.
![image](https://user-images.githubusercontent.com/27495644/131719120-80473ef6-ba60-4c0b-bc37-b768d2875e03.png)

2021-09-02 08:15 UTC, ashish10677 requested changes

2021-09-02 08:15 UTC, ashish10677 commented on utils/math.go
> +	return amountInWei
No need to return a value if you're not using it.

2021-09-02 08:15 UTC, ashish10677 commented on cmd/delegate.go
> +		utils.GetAmountWithChecks(valueInWei, balance)
Change the name of this function, to something like `CheckAmountAndBalance`. The `get` word doesn't make much sense here as we are not getting any value here.

2021-09-02 08:15 UTC, ashish10677 commented on cmd/delegate.go
> +		log.Infof("Delegating razors to Staker %s", _stakerId)
Can you convert the values in RZR and then display those here. Even if you have to show it in decimals.

2021-09-06 13:25 UTC, Yashk767 commented on utils/math.go
> +	return amountInWei
Actually we are using  the return value while testing the function.
ref - https://github.com/razor-network/razor-go/blob/develop/utils/math_test.go#L264

2021-09-07 11:32 UTC, ashish10677 approved these changes

2021-09-07 11:32 UTC, merged