Auto unstake and withdraw if stake < minStake while voting
razor-network/razor-go pull request #181
Opened 2021-09-01 14:31 UTC by Yashk767

Closes #179

2021-09-01 17:41 UTC, ashish10677 requested changes

2021-09-01 17:41 UTC, ashish10677 commented on cmd/vote.go
> +			log.Fatal("Stopped voting as total stake is already withdrawn.")
Let this be log.Error for now. We'll see if we want to stop the process or let it continue.

2021-09-01 17:41 UTC, ashish10677 commented on cmd/vote.go
> +	txn, err := stakeManager.Unstake(txnOpts, epoch, stakerId, txnArgs.Amount)
I was thinking, can you create an `unstake` function in` unstake.go` and then call that function from here itself. We can save a lot of code duplication.

2021-09-01 17:47 UTC, Yashk767 commented on cmd/vote.go
> +			log.Fatal("Stopped voting as total stake is already withdrawn.")
Even if we don't stop the execution, it will be stopped when it will try to unstake again by throwing error of non positive stake. So should we keep the same or change it to log.Error?

2021-09-01 17:48 UTC, ashish10677 commented
Link the issue here as well.

2021-09-01 17:49 UTC, ashish10677 commented on cmd/vote.go
> +			log.Fatal("Stopped voting as total stake is already withdrawn.")
Change everywhere to log.Error in vote.go, and return after logging error. Don't stop it by running log.Fatal.

2021-09-01 17:51 UTC, Yashk767 commented on cmd/vote.go
> +	txn, err := stakeManager.Unstake(txnOpts, epoch, stakerId, txnArgs.Amount)
Yeah I was thinking to do that but the issue was related to voting so I didn't change there. So should I create the separate unstake function in the same issue PR ?

2021-09-01 17:52 UTC, Yashk767 commented on cmd/vote.go
> +			log.Fatal("Stopped voting as total stake is already withdrawn.")
Okay, I will change it.

2021-09-01 17:52 UTC, ashish10677 commented on cmd/vote.go
> +	txn, err := stakeManager.Unstake(txnOpts, epoch, stakerId, txnArgs.Amount)
Yeah you can do that, since it is not any issue but only code reformatting.

2021-09-02 08:19 UTC, ashish10677 approved these changes

2021-09-02 08:19 UTC, merged