v0.1.6 support implemented
razor-network/razor-go pull request #182
Opened 2021-09-06 10:28 UTC by ashish10677

There are quite a few changes in `v0.1.6` support:
* There are 5 states now
* The last state has a claimBlockReward function call.
* Voting is only done on collections now
* The data type and order of parameters is changed in a lot of functions.

Closes #137

2021-09-07 12:34 UTC, Yashk767 requested changes

2021-09-07 12:34 UTC, Yashk767 commented on cmd/unstake.go
> +		epoch, err := WaitForCommitState(client, address, "unstake")
Can we not use Unstake and AutoWithdraw functions directly ?

2021-09-07 12:34 UTC, Yashk767 commented on cmd/cmd-utils.go
> +			log.Infof("Can only %s during dispute or confirm state. Retrying in 5 seconds...", accountAddress)
It should be action instead of accountAddress here.
 log.Infof("Can only %s during dispute or confirm state. Retrying in 5 seconds...",  action)

2021-09-07 12:48 UTC, ashish10677 commented on cmd/cmd-utils.go
> +			log.Infof("Can only %s during dispute or confirm state. Retrying in 5 seconds...", accountAddress)
Okay yes

2021-09-07 13:36 UTC, ashish10677 commented on cmd/unstake.go
> +		epoch, err := WaitForCommitState(client, address, "unstake")
Yeah, I guess while merging this was ommitted.

2021-09-07 14:13 UTC, ashish10677 commented on cmd/unstake.go
> +		stakerId, err := utils.GetStakerId(client, address)
So, this would also be the case in withdrawal right?

2021-09-07 14:19 UTC, Yashk767 commented on cmd/unstake.go
> +		stakerId, err := utils.GetStakerId(client, address)
yes in the case of delegator, we would need it in withdraw and  resetLock too.

2021-09-07 20:09 UTC, ashish10677 commented on cmd/unstake.go
> +		stakerId, err := utils.GetStakerId(client, address)
Ok, I'll change that then

2021-09-08 10:39 UTC, ashish10677 commented on cmd/unstake.go
> +		stakerId, err := utils.GetStakerId(client, address)
Done @Yashk767

2021-09-09 05:33 UTC, Yashk767 approved these changes

2021-09-09 06:53 UTC, merged