Test stake
razor-network/razor-go pull request #223
Opened 2021-09-16 14:32 UTC by Yashk767

closes #195

2021-09-16 14:42 UTC, Yashk767 commented
I have not included the flag inputs and related util methods which are required to derive txnArgs in stake function as we need txnArgs in approve() function as well.
e.g functions like `utils.AssignPassword(cmd.Flags())`, `utils.ConnectToClient(config.Provider)`,   `balance, err := utils.FetchBalance(client, address)` ). So those functions will be tested in some other command function (eg. In delegate.go, we only have one function i.e delegate so we can include those functions in delegate  itself and get them tested there.)

2021-09-17 06:36 UTC, ashish10677 commented
> I have not included the flag inputs and related util methods which are required to derive txnArgs in stake function as we need txnArgs in approve() function as well.
> e.g functions like `utils.AssignPassword(cmd.Flags())`, `utils.ConnectToClient(config.Provider)`, `balance, err := utils.FetchBalance(client, address)` ). So those functions will be tested in some other command function (eg. In delegate.go, we only have one function i.e delegate so we can include those functions in delegate itself and get them tested there.)

It's okay that they are not tested here, but since these are `utils` functions, shouldn't they be tested in the `utils` package?

2021-09-17 06:56 UTC, ashish10677 requested changes

2021-09-17 06:56 UTC, ashish10677 commented on cmd/interface.go
> +	Stake(*bind.TransactOpts, uint32, *big.Int, *ethclient.Client) (*Types.Transaction, error)
Can you keep *ethclient.Client as the first parameter?

2021-09-17 07:17 UTC, Yashk767 commented
> > I have not included the flag inputs and related util methods which are required to derive txnArgs in stake function as we need txnArgs in approve() function as well.
> > e.g functions like `utils.AssignPassword(cmd.Flags())`, `utils.ConnectToClient(config.Provider)`, `balance, err := utils.FetchBalance(client, address)` ). So those functions will be tested in some other command function (eg. In delegate.go, we only have one function i.e delegate so we can include those functions in delegate itself and get them tested there.)
> 
> It's okay that they are not tested here, but since these are `utils` functions, shouldn't they be tested in the `utils` package?

True, I was saying it on a coverage perspective. As we could not include those functions in stake than will the coverage here be fulfilled I am not sure , if not than how can I do it ?

2021-09-17 07:21 UTC, ashish10677 commented
> > > I have not included the flag inputs and related util methods which are required to derive txnArgs in stake function as we need txnArgs in approve() function as well.
> > > e.g functions like `utils.AssignPassword(cmd.Flags())`, `utils.ConnectToClient(config.Provider)`, `balance, err := utils.FetchBalance(client, address)` ). So those functions will be tested in some other command function (eg. In delegate.go, we only have one function i.e delegate so we can include those functions in delegate itself and get them tested there.)
> > 
> > 
> > It's okay that they are not tested here, but since these are `utils` functions, shouldn't they be tested in the `utils` package?
> 
> True, I was saying it on a coverage perspective. As we could not include those functions in stake than will the coverage here be fulfilled I am not sure , if not than how can I do it ?

It should be fulfilled I guess. Let's see once coveralls is integrated. For the time being it is fine.

2021-09-17 08:31 UTC, ashish10677 approved these changes
LGTM

2021-09-17 11:29 UTC, ashish10677 commented
Leaving for @SkandaBhat to merge. Looks good to me.

2021-09-20 12:57 UTC, ashish10677 commented
@Yashk767 please resolve the conflicts.

2021-09-21 09:28 UTC, SkandaBhat approved these changes

2021-09-21 09:28 UTC, SkandaBhat commented
@Yashk767 what is the test coverage percentage?

2021-09-21 09:32 UTC, Yashk767 commented
> @Yashk767 what is the test coverage percentage?

Coverage is not implemented right ?
Is there any other way where I can get it

2021-09-21 09:32 UTC, SkandaBhat commented
Run locally and check

2021-09-21 10:16 UTC, Yashk767 commented
> @Yashk767 what is the test coverage percentage?

Its 100% for stakeCoins function.

2021-09-21 10:20 UTC, SkandaBhat commented
What is the overall percentage?


> > @Yashk767 what is the test coverage percentage?
> 
> Its 100% for stakeCoins function.

2021-09-21 10:25 UTC, Yashk767 commented
> What is the overall percentage?
> 
> > > @Yashk767 what is the test coverage percentage?
> > 
> > 
> > Its 100% for stakeCoins function.

coverage: 20.5% of statements
Overall

2021-09-21 10:32 UTC, merged