Test createJob
razor-network/razor-go pull request #230
Opened 2021-09-17 16:50 UTC by Yashk767

Closes #196

2021-09-17 17:33 UTC, ashish10677 requested changes

2021-09-17 17:33 UTC, ashish10677 commented on cmd/createJob_test.go
> +			name: "Test1: When createJob transaction is succesull",
Successful spelling is wrong

2021-09-17 17:33 UTC, ashish10677 commented on cmd/createJob.go
>  		power, _ := cmd.Flags().GetInt8("power")
What happens if no value is provided for power? Add a test case for that as well

2021-09-20 07:05 UTC, Yashk767 commented on cmd/createJob.go
>  		power, _ := cmd.Flags().GetInt8("power")
But we are not checking value of power flag in createJob function, how can I test it .

2021-09-20 12:54 UTC, ashish10677 commented on cmd/createJob.go
>  		power, _ := cmd.Flags().GetInt8("power")
Then you have to handle that in code as well. That is why test case is required.

2021-09-24 07:29 UTC, ashish10677 requested changes

2021-09-24 07:29 UTC, ashish10677 commented on cmd/createJob.go
> +		return common.Hash{0x00}, err
Please use core.NilHash instead of common.Hash{0x00}

2021-09-27 06:35 UTC, ashish10677 commented
Can you please report the coverage for this and all subsequent PRs for testing?

2021-09-27 06:36 UTC, ashish10677 approved these changes

2021-09-27 06:58 UTC, Yashk767 commented
> Can you please report the coverage for this and all subsequent PRs for testing?

With go test -cover ./... , I can only check coverage for respective packages, as we are currently writing tests for cmd so I can report coverage for cmd package with every PR.

2021-09-27 07:09 UTC, SkandaBhat commented
Is this up to date with main? We have coveralls on main

2021-09-27 08:25 UTC, Yashk767 commented
The overall coverage is `5.1%`

Coverage for respective packages : 
```
?       razor   [no test files]
?       razor/accounts  [no test files]
ok      razor/cmd       0.014s  coverage: 21.3% of statements
?       razor/core      [no test files]
?       razor/core/types        [no test files]
?       razor/logger    [no test files]
?       razor/path      [no test files]
?       razor/pkg/bindings      [no test files]
ok      razor/utils     0.144s  coverage: 14.5% of statements


```

2021-09-27 08:26 UTC, merged