Timeout Set for waitForBlockFunction in common.go
razor-network/razor-go pull request #25
Opened 2021-06-29 16:18 UTC by Yashk767

Resolve #15

2021-06-29 16:43 UTC, ashish10677 approved these changes
LGTM

2021-07-02 06:06 UTC, SkandaBhat requested changes

2021-07-02 06:11 UTC, Yashk767 commented on utils/common_test.go
> -package utils
As this file would contain tests for merkle tree functions and the these tests are already present in the go-merkletree package.

2021-07-02 06:13 UTC, Yashk767 commented on utils/array_test.go
> +		{
It was added just to test the edge case when both array and value is nil.

2021-07-05 10:48 UTC, ashish10677 approved these changes

2021-07-06 07:09 UTC, SkandaBhat approved these changes
LGTM

2021-07-06 07:09 UTC, merged