Added tests for GetAmountWithChecks and performAggregation
razor-network/razor-go pull request #34
Opened 2021-07-02 16:54 UTC by Yashk767

resolve #21 
- Added test cases for functions like GetAmountWithChecks and performAggregation in utils/math_test.go

2021-07-03 20:00 UTC, ashish10677 requested changes

2021-07-05 06:11 UTC, Yashk767 commented on utils/math_test.go
> +			want: big.NewInt(1).Mul(big.NewInt(0), big.NewInt(1e18)),
If I put want : big.NewInt(0) , the test is failing . I guess when we are multiplying the amount with 1e18 , it is getting typecasted.

2021-07-05 06:39 UTC, ashish10677 commented on utils/math_test.go
> +			want: big.NewInt(1).Mul(big.NewInt(0), big.NewInt(1e18)),
I would suggest you use got.Cmp(want) == 0, instead of reflect.DeepEqual for testing big.Int values,
```
a := big.NewInt(0)
b := big.NewInt(1).Mul(big.NewInt(0), big.NewInt(1e18))
fmt.Println(a.Cmp(b) == 0)
```
This does return true.

2021-07-05 06:40 UTC, Yashk767 commented on utils/math_test.go
> +			want: big.NewInt(1).Mul(big.NewInt(0), big.NewInt(1e18)),
Yes, will follow this one.

2021-07-05 07:12 UTC, ashish10677 commented on utils/math_test.go
> +			if got.Cmp(tt.want)!=0 {
Add a space before and after `!=0`

2021-07-06 06:58 UTC, SkandaBhat approved these changes

2021-07-06 06:58 UTC, merged