Test unstake
razor-network/razor-go pull request #350
Opened 2021-11-18 11:05 UTC by Yashk767

# Description

- Seperated unstake function into initialiseUnstake, executeUnstake and unstake
- Tests for unstake command.

Fixes #207

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-11-22 06:23 UTC, ashish10677 requested changes

2021-11-22 06:23 UTC, ashish10677 commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
Why is this commented out?

2021-11-22 06:23 UTC, ashish10677 commented on cmd/unstake.go
> +func Unstake(config types.Configurations, client *ethclient.Client, address string, password string, valueInWei *big.Int, stakerId uint32, utilsStruct UtilsStruct) (types.TransactionOptions, error) {
Can you pass these details which you get from the flags as a single struct.
```
type struct data {
    address string
    password string
    valueInWei *big.Int
    stakerId uint32
}
```

2021-11-22 06:23 UTC, ashish10677 commented on cmd/unstake_test.go
> +					Amount: big.NewInt(0),
Does the amount have to be 0 here? If no, then put a realistic value.

2021-11-22 06:23 UTC, ashish10677 commented on cmd/unstake_test.go
> +		//{
If this test isn't required then delete these lines.

2021-11-22 08:29 UTC, Yashk767 commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
There is good amount of wait time in AutoWithdraw thus its not being tested

2021-11-22 08:31 UTC, Yashk767 commented on cmd/unstake_test.go
> +					Amount: big.NewInt(0),
Yes it should be 0 as we have a check of existing lock for unstake, If there is existing one than lock.Amount >0.

2021-11-22 09:37 UTC, ashish10677 commented on cmd/unstake_test.go
> +					Amount: big.NewInt(0),
Okay 👍

2021-11-22 15:28 UTC, ashish10677 commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
@SkandaBhat we need to discuss about this, what should be done.

2021-11-23 12:58 UTC, SkandaBhat commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
What is this?

2021-11-23 12:59 UTC, ashish10677 commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
While testing unstake and autowithdraw, we need to wait for the lock period to get over. This increases the overall time taken to test the unstake function. What should we do about that?

2021-11-25 09:42 UTC, Yashk767 commented on cmd/unstake_test.go
> +//func TestAutoWithdraw(t *testing.T) {
As discussed, I have created mock for sleep function, and added tests for AutoWithdraw.

2021-11-25 10:07 UTC, ashish10677 approved these changes

2021-11-26 07:33 UTC, SkandaBhat approved these changes

2021-11-26 07:33 UTC, merged