feat: Adding docker-compose.yml
razor-network/razor-go pull request #365
Opened 2021-11-23 13:04 UTC by Shrikant1212

# Description
Configured docker-compose support for deployment

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?
We can run razor-go with command `docker-compose up -d`
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-23 13:27 UTC, ashish10677 commented
@Shrikant1212 can you update the README as well?

2021-11-24 06:11 UTC, ashish10677 requested changes

2021-11-24 06:11 UTC, ashish10677 commented on README.md
>  You need to set a provider before you can operate razor-go cli on docker:
Just saw this, `setconfig` isn't the correct command. It is `setConfig`. Can you please update this as well.

2021-11-24 06:11 UTC, ashish10677 commented on README.md
> +- `geth` and `abigen` should be installed. (Skip this step if you don't want to fetch the bindings and build from scratch)
I think `solc` and `jq` are a pre requisite as well

2021-11-24 06:11 UTC, ashish10677 commented on README.md
> +\_\_Before staking on Razor Network, please ensure your account has eth and RAZOR. For testnet RAZOR, please contact us on Discord.
Why 2 underscores here? The goal is to make this text italics.

2021-11-24 09:35 UTC, ashish10677 approved these changes
LGTM

2021-11-24 13:54 UTC, SkandaBhat commented on docker-compose.yml
> +    #platform: linux/x86_64 #Uncomment for silicon based MAC
Remove this and add platform in readme

2021-11-26 07:36 UTC, merged