Unstake Input fix
razor-network/razor-go pull request #387
Opened 2021-12-03 19:34 UTC by Yashk767

# Description

The input value for unstake is considered in RZR's and than it is converted into its equivalent sRZR's that is passed as parameter to unstake contract call.

Fixes #376

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-12-06 09:06 UTC, ashish10677 requested changes

2021-12-06 09:06 UTC, ashish10677 commented on cmd/unstake.go
> +	stakedToken := utilsStruct.razorUtils.GetStakedToken(client, staker.TokenAddress)
Can you move this entire process of getting balance of sRzr to a new function.

2021-12-06 09:39 UTC, Yashk767 commented on cmd/unstake.go
> +	stakedToken := utilsStruct.razorUtils.GetStakedToken(client, staker.TokenAddress)
yes

2021-12-07 08:15 UTC, ashish10677 commented on cmd/unstake.go
> +	log.Infof("The maximum RZRs you can unstake: %f RZRs", utilsStruct.razorUtils.GetAmountInDecimal(maxUnstake))
Make this log.Debugf

2021-12-07 08:16 UTC, Yashk767 commented on cmd/unstake.go
> +	log.Infof("The maximum RZRs you can unstake: %f RZRs", utilsStruct.razorUtils.GetAmountInDecimal(maxUnstake))
okay

2021-12-07 08:17 UTC, ashish10677 commented on cmd/unstake_test.go
> +			name: "Test 5: When there is an error in converting RZR's to sRZR's",
Add one more test case with real world values, where the supply is 1 billion razors.

2021-12-07 08:18 UTC, ashish10677 commented on utils/math_test.go
> +	}
Add tests here with higher values as well.

2021-12-07 08:18 UTC, ashish10677 requested changes

2021-12-07 08:18 UTC, ashish10677 commented on utils/math_test.go
> +		},
Same thing here.

2021-12-07 11:07 UTC, ashish10677 approved these changes

2021-12-07 11:08 UTC, merged