configure publish step
razor-network/razor-go pull request #390
Opened 2021-12-06 14:33 UTC by Shrikant1212

# Description
Configuring Circle-CI to build/publish image to dockerhub
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Contracts version:
* Hardware:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-09 07:16 UTC, ashish10677 approved these changes
lgtm

2021-12-13 08:25 UTC, SkandaBhat requested changes

2021-12-13 08:25 UTC, SkandaBhat commented on .circleci/config.yml
> +          context: Build
What is this context?

2021-12-15 09:05 UTC, Kaizoku-Shrikant commented on .circleci/config.yml
> +          context: Build
We use Context to store ENV variables in CircleCI

2021-12-20 08:50 UTC, SkandaBhat approved these changes

2021-12-20 08:53 UTC, merged