Coverage of propose.go made 100%
razor-network/razor-go pull request #403
Opened 2021-12-07 14:12 UTC by ashish10677

Fixes #192

2021-12-13 08:23 UTC, SkandaBhat requested changes

2021-12-13 08:23 UTC, SkandaBhat commented on cmd/propose.go
> +	for i := 0; i < 10000000; i++ {
Why was this number changed?

2021-12-13 08:40 UTC, ashish10677 commented on cmd/propose.go
> +	for i := 0; i < 10000000; i++ {
10000000000 is a very big number, and if the iteration goes almost till that number, it is likely that your block will not be included in the maxAltBlocks. This also slowed down testing if we want to go to the last return after the `for` loop. Hence, I shortened the value.

2021-12-13 08:45 UTC, SkandaBhat commented on cmd/propose.go
> +	for i := 0; i < 10000000; i++ {
Needs to be accounted for in a separate issue to make sure we document it

2021-12-15 07:42 UTC, ashish10677 commented
Will open a new PR wrt change in the iteration max value.

2021-12-15 07:42 UTC, closed without merging