Rogue mode for commit only
razor-network/razor-go pull request #407
Opened 2021-12-09 14:01 UTC by ashish10677

# Description

You can specify `--rogue --rogueMode commit` to the vote command to report wrong values during the commit state.

Fixes #399 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Tested on local hardhat

**Test Configuration**:
* Contracts version: v0.1.76
* Hardware: Macbook m1 air

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-13 08:09 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +		//contains        bool
Why is this commented?

2021-12-13 08:09 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +				//contains: true,
Remove comment

2021-12-13 08:10 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +				//contains: true,
Remove comment

2021-12-13 08:10 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +				//contains: true,
Remove comment

2021-12-13 08:10 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +				//contains:        true,
Remove comment

2021-12-13 08:10 UTC, SkandaBhat commented on cmd/cmd-utils_test.go
> +			//
Remove comment

2021-12-13 08:13 UTC, SkandaBhat commented on cmd/vote.go
> +		rogue := types.Rogue{
Call it rogueObject or rogueData. Just rogue makes it seem like a bool.

2021-12-13 08:16 UTC, ashish10677 commented on cmd/vote.go
> +		rogue := types.Rogue{
Ok

2021-12-13 08:22 UTC, SkandaBhat requested changes
.

2021-12-15 07:31 UTC, ashish10677 commented on cmd/cmd-utils_test.go
> +		//contains        bool
I'll remove the comment. `contains` is no longer required.

2021-12-20 08:51 UTC, SkandaBhat approved these changes

2021-12-20 08:54 UTC, merged