Mockery options
razor-network/razor-go pull request #412
Opened 2021-12-17 14:53 UTC by Yashk767

# Description

Used Mockery for testing options.go

2021-12-22 04:52 UTC, ashish10677 requested changes

2021-12-22 04:52 UTC, ashish10677 commented on utils/math_test.go
> +//func TestMultiplyFloatAndBigInt(t *testing.T) {
Why has this been commented out?

2021-12-22 04:52 UTC, ashish10677 commented on utils/api_test.go
> +		//{
Remove this entirely, no need to comment it out.

2021-12-22 05:28 UTC, Yashk767 commented on utils/math_test.go
> +//func TestMultiplyFloatAndBigInt(t *testing.T) {
Oh we changed the method caller there so I commented that time. I will uncomment it now.

2021-12-23 09:22 UTC, ashish10677 commented
@Yashk767 please resolve conflicts.

2021-12-24 07:59 UTC, ashish10677 approved these changes

2021-12-24 07:59 UTC, merged