Feature estimate gas
razor-network/razor-go pull request #486
Opened 2022-01-14 12:19 UTC by Yashk767

# Description

Added condition to send max gasLimit when the estimateGas throws an error which is an rpc error or too low intrinsic gas error

Fixes #345

2022-01-14 12:28 UTC, ashish10677 requested changes

2022-01-14 12:28 UTC, ashish10677 commented on utils/options.go
> +			latestBlock, err := UtilsInterface.GetLatestBlockWithRetry(transactionData.Client)
Can you put a debug log saying why we are sending block gas limit

2022-01-14 12:30 UTC, Yashk767 commented on utils/array.go
> +func ContainsStringFromArray(source string, subStringArray []string) bool {
But we are checking for substring here, the existing one will check for the entire string right ?

2022-01-14 12:35 UTC, Yashk767 commented on utils/array.go
> +func ContainsStringFromArray(source string, subStringArray []string) bool {
Here we are checking whether any string from array is a sub-string of source string

2022-01-19 10:38 UTC, ashish10677 commented on utils/array.go
> +func ContainsStringFromArray(source string, subStringArray []string) bool {
Okay got it

2022-01-19 10:43 UTC, ashish10677 approved these changes

2022-01-20 07:34 UTC, merged