added link to contribution.md in readme.md
razor-network/razor-go pull request #50
Opened 2021-07-07 13:03 UTC by anshme

2021-07-07 13:36 UTC, ashish10677 requested changes

2021-07-07 13:36 UTC, ashish10677 commented on README.md
> +We would really appreciate your contribution. To see our contribution guideline please check https://github.com/razor-network/razor-go/blob/main/.github/CONTRIBUTING.md
Can you change the last line to: `To see our contribution guidelines please check here` and put a link in `here`?

2021-07-07 17:07 UTC, ashish10677 approved these changes

2021-07-08 13:16 UTC, Yashk767 approved these changes

2021-07-08 13:19 UTC, ashish10677 commented
@anshme we cannot merge this since your first commit is not signed. In order to merge all the commits must be signed. Take a look at [this](https://docs.github.com/articles/about-gpg/) for reference. Open a new PR with signed commits.

2021-07-08 13:19 UTC, closed without merging