Added tests for utils/asset
razor-network/razor-go pull request #519
Opened 2022-01-25 11:25 UTC by shekhar2807

# Description

Tests have been added for utils/asset by using mockery and utils/api has also been refactored in this PR as it was prerequisite for util/asset.

Fixes #394 #393 
 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tests for all the function in utils/asset
- [x] Tests refactored  for utils/api

**Test Configuration**:
* Contracts version: 
* Hardware: MacBook M1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-01-27 09:52 UTC, Yashk767 approved these changes
LGTM

2022-01-27 09:53 UTC, ashish10677 requested changes

2022-01-27 10:57 UTC, shekhar2807 commented on utils/asset_test.go
> +	collection := bindings.StructsCollection{Active: true, Id: 2, AssetIndex: 1, Power: 2,
Done @ashish10677

2022-01-31 12:07 UTC, ashish10677 approved these changes

2022-01-31 12:09 UTC, merged