Test give sorted
razor-network/razor-go pull request #569
Opened 2022-02-14 05:58 UTC by Yashk767

# Description

Added tests for giveSorted function present in dispute.go

Fixes #193

2022-02-14 11:49 UTC, ashish10677 requested changes

2022-02-14 11:49 UTC, ashish10677 commented on cmd/dispute_test.go
> +			},
No check for the time if the error is "gas limit reached"?

2022-02-15 05:46 UTC, Yashk767 commented on cmd/dispute_test.go
> +			},
It was not added as It gets stuck in the recursion loop once it enters.

2022-02-15 14:15 UTC, ashish10677 requested changes

2022-02-15 14:15 UTC, ashish10677 commented on cmd/dispute_test.go
> +			},
It should not get stuck if the code is correct imo. Can you put a debugger and check why exactly it is getting stuck. If it is getting stuck, we might need to revisit the code.

2022-02-16 13:06 UTC, Yashk767 commented on cmd/dispute_test.go
> +			},
Added the test case for recursive call now.

2022-02-17 08:16 UTC, ashish10677 commented on cmd/dispute_test.go
> +				sortedStakers: []uint32{2, 1, 3, 5},
Can you increase the number of sortedStakers for this test. Anywhere around 15-20 will be good. You can keep this test and add one more test with more number of stakers.

2022-02-17 11:19 UTC, ashish10677 approved these changes
LGTM

2022-02-17 12:56 UTC, merged