Added tests for utils/common.go
razor-network/razor-go pull request #573
Opened 2022-02-14 15:43 UTC by shekhar2807

-Tests added for utils/common.go
-fixes #523

2022-02-14 18:45 UTC, SkandaBhat requested changes
please fix the comments

2022-02-14 18:45 UTC, SkandaBhat commented on addresses.json
> +}
unnecessary change. please revert.

2022-02-14 18:45 UTC, SkandaBhat commented on cmd/struct-utils.go
> +	return utils.UtilsInterface.GetEpoch(client)
Can we not instantiate utils.UtilsInterface and use that on every line? There is too much code duplication. Please fix.

2022-02-17 12:57 UTC, SkandaBhat commented
@shekhar2807 there are conflicts in this PR

2022-02-22 09:46 UTC, ashish10677 requested changes

2022-02-22 09:46 UTC, ashish10677 commented on utils/common.go
> +	return UtilsInterface.BalanceOf(coinContract, &opts, address)
`UtilsInterface.BalanceOf` makes less sense. Can you make it `CoinInterface.BalanceOf` or something similar?

2022-02-22 09:46 UTC, ashish10677 commented on utils/common.go
> +		transactionStatus := UtilsInterface.CheckTransactionReceipt(client, hashToRead)
Can you make `UtilsInterface.CheckTransactionReceipt` as `TransactionUtils.CheckTransactionReceipt`?

2022-02-22 09:46 UTC, ashish10677 commented on utils/common.go
> +	ethBalance, err := Client.BalanceAt(client, context.Background(), common.HexToAddress(address), nil)
Why is client being passed as an extra parameter?
My understanding was it'll be `Client.BalanceAt(...)` and the `Client` will contain `client` which is essentially `*ethclient.Client`.

2022-02-22 11:10 UTC, shekhar2807 commented on utils/common.go
> +		transactionStatus := UtilsInterface.CheckTransactionReceipt(client, hashToRead)
This function is in utils/common.go only , so for changing this it would change whole pattern and this does not come under any native package. I think we can keep it as it is , let me know if you feel otherwise. cc @ashish10677

2022-02-23 07:30 UTC, ashish10677 commented on utils/common.go
> +	ethBalance, err := Client.BalanceAt(client, context.Background(), common.HexToAddress(address), nil)
Change Client to ClientInterface. So the call becomes, `ClientInterface.BalanceAt(...)`

2022-02-24 01:51 UTC, ashish10677 approved these changes

2022-02-28 05:17 UTC, SkandaBhat approved these changes

2022-02-28 07:14 UTC, merged