MakeBlock now stored and fetched from fileStorage
razor-network/razor-go pull request #576
Opened 2022-02-16 09:34 UTC by shekhar2807

DESCRIPTION :

-makeBlock now stored in file when called in propose and fetched from file when used in dispute.
-modified test according to makeBlock.
-renamed SaveCommittedDataToFile and ReadCommittedDataFromFile to SaveDataToFile and ReadDataFromFile for       readability purpose.
-added function convertUint32ArrayToBigIntArray and it's tests.

-fixes #487

2022-02-17 09:05 UTC, ashish10677 requested changes

2022-02-17 09:46 UTC, shekhar2807 commented on cmd/dispute.go
> +			log.Error("Error in getting file name to save median data: ", err)
Changed @ashish10677.

2022-02-17 12:35 UTC, shekhar2807 commented on cmd/dispute.go
> -	medians, err := cmdUtils.MakeBlock(client, account.Address, types.Rogue{IsRogue: false})
Done @ashish10677.

2022-02-18 05:29 UTC, ashish10677 approved these changes
LGTM

2022-02-18 05:30 UTC, merged