Configure metrices
razor-network/razor-go pull request #590
Opened 2022-02-25 13:10 UTC by Shrikant1212

# Description
 ## Expose metrics
We are exposing prometheus based metrics to monitor our staker, 

Fixes #425 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
To expose a metrics we ca use razor cli todo so, `./razor setConfig --exposeMetrics 2112`

2022-02-25 13:13 UTC, Shrikant1212 commented
@ashish10677  @SkandaBhat  please help in reviewing this, willl update Radme.me soon.

2022-03-03 11:13 UTC, Yashk767 submitted a review, later dismissed
LGTM

2022-03-09 08:00 UTC, SkandaBhat requested changes

2022-03-09 08:00 UTC, SkandaBhat commented on README.md
> +Can expose the prometheus based metrics for monitoring
Replace with "Expose Prometheus-based metrics for monitoring."

2022-03-09 12:12 UTC, SkandaBhat approved these changes
lgtm

2022-03-09 12:12 UTC, merged