Override jobs
razor-network/razor-go pull request #593
Opened 2022-02-26 13:31 UTC by Yashk767

# Description

Added override jobs functionality and fetching custom jobs data from assets.json file.

Fixes #561

2022-03-09 11:25 UTC, ashish10677 requested changes
Remove OverrideJobs command.

2022-03-09 11:25 UTC, ashish10677 commented on utils/asset.go
> +		if !Contains(overriddenJobIds, jobs) {
Change `jobs` to `id`

2022-03-14 12:48 UTC, ashish10677 commented
@Yashk767 please update the readme as well.

2022-03-14 13:29 UTC, Yashk767 commented
> @Yashk767 please update the readme as well.

Done

2022-03-15 05:21 UTC, ashish10677 requested changes

2022-03-15 05:21 UTC, ashish10677 commented on README.md
> +Jobs URLs are a placeholder for where to fetch values from. There is a chance that these URLs might either fail, or get razor nodes blacklisted, etc.
for should be from.

2022-03-15 05:21 UTC, ashish10677 commented on README.md
> +- Additional jobs tha you want to add to a collection should be added in `custom jobs` field with their respective URLs and selectors.
`tha` should be `that`

2022-03-15 05:21 UTC, ashish10677 commented on README.md
> +### Delete override
Are we still supporting delete override @SkandaBhat ? I don't think so.

2022-03-16 10:00 UTC, Yashk767 commented
Removed `deleteOverride` command.

2022-03-16 13:07 UTC, ashish10677 commented on README.md
> +### Delete override
@Yashk767 please remove this from README.

2022-03-16 18:47 UTC, Yashk767 commented on README.md
> +### Delete override
> @Yashk767 please remove this from README.

Done

2022-03-16 19:39 UTC, ashish10677 approved these changes

2022-03-16 19:39 UTC, merged