ETA added for withdraw
razor-network/razor-go pull request #616
Opened 2022-03-14 13:40 UTC by shekhar2807

# Description

-ETA added for withdraw . Now does not wait for the epoch where staker can withdraw the stake.

Fixes #611

2022-03-15 06:35 UTC, SkandaBhat requested changes
We also need to give approx time in seconds. "Please wait for 1 epoch! (approximately X seconds)"

2022-03-16 08:35 UTC, shekhar2807 commented
> We also need to give approx time in seconds. "Please wait for 1 epoch! (approximately X seconds)"

@SkandaBhat 
<img width="1395" alt="Screenshot 2022-03-16 at 2 02 47 PM" src="https://user-images.githubusercontent.com/65169767/158549144-6a821fce-8c1b-4269-b573-fe93a2bfa740.png">

2022-03-16 09:14 UTC, ashish10677 requested changes

2022-03-16 09:14 UTC, ashish10677 commented on cmd/withdraw.go
> +		log.Info("Withdrawal period not reached. Cannot withdraw now, please wait for", waitFor, "epochs!", "(approximately", razorUtils.SecondsToHuman(value), ")")
Can you just add a small check to see if the waitFor value is 1, then print epoch instead of epochs.
Also, use `log.Infof` here instead of `log.Info`

2022-03-16 09:14 UTC, ashish10677 commented on utils/time.go
> +func (*UtilsStruct) SecondsToHuman(input int) (result string) {
Change this name to `SecondsToReadableTime` or `SecondsToTime`.

2022-03-16 09:14 UTC, ashish10677 commented on utils/time.go
> +func plural(count int, singular string) (result string) {
remove `result` as return variable here and add return result at last.
This is not wrong, but we are not using this format anywhere else imo. Just to maintain consistency.

2022-03-16 13:02 UTC, shekhar2807 commented on cmd/withdraw.go
> +		log.Info("Withdrawal period not reached. Cannot withdraw now, please wait for", waitFor, "epochs!", "(approximately", razorUtils.SecondsToHuman(value), ")")
Done @ashish10677

2022-03-16 13:02 UTC, shekhar2807 commented on utils/time.go
> +func (*UtilsStruct) SecondsToHuman(input int) (result string) {
Done @ashish10677

2022-03-16 13:02 UTC, shekhar2807 commented on utils/time.go
> +func plural(count int, singular string) (result string) {
Done @ashish10677

2022-03-16 13:08 UTC, ashish10677 approved these changes
LGTM

2022-03-16 19:32 UTC, merged