Exit ongoing for loop on state change
razor-network/razor-go pull request #617
Opened 2022-03-16 09:27 UTC by Yashk767

# Description

Added a timer to `for` loop which takes enough time to execute and passes the current state time.

Following are the functions where timer is implemented
- [ ] propose - Getiteration
- [ ] Dispute
- [ ] GetBiggestStakeAndId
- [ ]  GetSortedVotes
- [ ] GetLastProposedEpoch

Fixes #577

2022-03-22 08:49 UTC, ashish10677 commented
@Yashk767 please resolve the conflicts

2022-03-27 20:46 UTC, ashish10677 requested changes

2022-03-29 11:55 UTC, Yashk767 commented on cmd/propose.go
> +	bufferPercent, err := cmdUtils.GetBufferPercent()
We need both buffer percent and state buffer to calculate the remaining time of state. 
Used both in state remaining time calculation in ` GetRemainingTimeOfCurrentState()` in common.go.

2022-03-30 07:26 UTC, SkandaBhat commented
1. For each loop, add a blocking wait call
2. Run staker normally
3. test if each loop breaks 
4. test functionality of staker

2022-03-31 06:59 UTC, Yashk767 commented
> 1. For each loop, add a blocking wait call
> 2. Run staker normally
> 3. test if each loop breaks
> 4. test functionality of staker

It is working fine.

2022-03-31 07:26 UTC, merged