Logging mechanism improvement
razor-network/razor-go pull request #628
Opened 2022-03-22 14:57 UTC by shekhar2807

# Description

- New flag has been added in every command named as logFile where user can pass the file name where they want to store       the logs of that command . If the flag is not passed output will be only printed on terminal and will not be stored anywhere.

Fixes #581

2022-03-23 06:05 UTC, ashish10677 requested changes

2022-03-23 06:05 UTC, ashish10677 commented on logger/logger.go
> +		_, err := path.PathUtilsInterface.GetLogFilePath(fileName)
If log fileName isn't provided just write to stdout, you don't need to fetch the path.

2022-03-23 06:05 UTC, ashish10677 commented on cmd/addStake.go
> +		LogFile           string
Instead of explicitly adding a logFile flag in every command, can you not add it in global way so that all commands by default have it? Like logLevel, or gasPrice, etc.

2022-03-23 06:09 UTC, ashish10677 commented on cmd/addStake.go
> +	cmdUtils.AssignLogFile(flagSet)
`logger.Address = address` can be present in AssignLogFile function itself I think

2022-03-23 07:28 UTC, ashish10677 commented on README.md
> +
Add a note here regarding multiple commands running with same log file

2022-03-25 11:22 UTC, ashish10677 commented
@SkandaBhat according to this PR, the logFile will be always stored in `.razor` directory. I don't think that is the requirement. The flag `--logFile` must take the entire path and create a file at that path. Not specifically in the `.razor` directory.

2022-03-28 07:22 UTC, ashish10677 requested changes

2022-03-28 07:22 UTC, ashish10677 commented on README.md
> +_The logs for above command will be stored in stakingLogs.log file in .razor directory_
Mention the full path here

2022-03-28 07:34 UTC, shekhar2807 commented on README.md
> +_The logs for above command will be stored in stakingLogs.log file in .razor directory_
Done @ashish10677

2022-03-28 07:38 UTC, ashish10677 approved these changes

2022-03-28 07:38 UTC, merged