Coverage increased in utils
razor-network/razor-go pull request #671
Opened 2022-04-07 08:21 UTC by shekhar2807

# Description

-Tests added for utils which were not covered in V1.

Fixes #667

2022-04-08 07:34 UTC, ashish10677 commented
@shekhar2807 please write tests for merkle.go

2022-04-08 09:17 UTC, shekhar2807 commented
> @shekhar2807 please write tests for merkle.go

Done @ashish10677

2022-04-08 20:19 UTC, ashish10677 requested changes

2022-04-08 20:19 UTC, ashish10677 commented on utils/merkle_test.go
> +			want: [][][]byte{{{52, 34, 71, 138, 66, 123, 171, 13, 20, 101, 234, 111, 34, 80, 119, 150, 191, 7, 189, 164, 50, 31, 68, 19, 51, 45, 101, 139, 128, 81, 172, 181}}, {{182, 253, 152, 238, 183, 224,
Please write a few more test cases with varied values.

2022-04-08 20:19 UTC, ashish10677 commented on utils/merkle_test.go
> +			want: [][][]byte{{{52, 34, 71, 138, 66, 123, 171, 13, 20, 101, 234, 111, 34, 80, 119, 150, 191, 7, 189, 164, 50, 31, 68, 19, 51, 45, 101, 139, 128, 81, 172, 181}}, {{182, 253, 152, 238, 183, 224,
Add tests if values is even, odd or 0.

2022-04-08 20:19 UTC, ashish10677 commented on utils/merkle_test.go
> +		},
Write tests if tree is nil or has no elements

2022-04-08 20:19 UTC, ashish10677 commented on utils/merkle_test.go
> +	}
What happens if tree is nil

2022-04-08 21:55 UTC, shekhar2807 commented on utils/merkle_test.go
> +			want: [][][]byte{{{52, 34, 71, 138, 66, 123, 171, 13, 20, 101, 234, 111, 34, 80, 119, 150, 191, 7, 189, 164, 50, 31, 68, 19, 51, 45, 101, 139, 128, 81, 172, 181}}, {{182, 253, 152, 238, 183, 224,
Done @ashish10677

2022-04-08 21:55 UTC, shekhar2807 commented on utils/merkle_test.go
> +		},
Done @ashish10677

2022-04-08 21:56 UTC, shekhar2807 commented on utils/merkle_test.go
> +	}
The test does not run for this particular case . @ashish10677

2022-04-11 07:42 UTC, ashish10677 requested changes

2022-04-11 07:42 UTC, ashish10677 commented on utils/merkle_test.go
> +	}
Can you write that test when tree is nil.

2022-04-11 08:07 UTC, shekhar2807 commented on utils/merkle_test.go
> +	}
Done  @ashish10677

2022-04-11 08:20 UTC, ashish10677 approved these changes

2022-04-11 08:20 UTC, merged