Godoc documentation for utils, logger, core, matrices
razor-network/razor-go pull request #717
Opened 2022-05-19 20:25 UTC by shekhar2807

# Description

-Comments added for utils, core, types, logger, metrics for the godoc documentation.
-To generate the documentation :

$ godoc -http=127.0.0.1:6060 

or just the port 

$ godoc -http=:6060

fixes #687 
fixes #712

2022-05-20 11:00 UTC, ashish10677 requested changes

2022-05-20 11:21 UTC, shekhar2807 commented on logger/logger.go
> +//This function returns the new logger
Done @ashish10677

2022-05-20 11:21 UTC, shekhar2807 commented on logger/logger.go
> +//This function allow us use formatting features to create descriptive error messages
Done @ashish10677

2022-05-23 08:48 UTC, ashish10677 approved these changes

2022-05-23 08:48 UTC, merged