Feature testing
razor-network/razor-go pull request #72
Opened 2021-07-23 14:04 UTC by Yashk767

- Test file created for cmd/stake.go
- Includes tests for approve and stakeCoins function

2021-07-26 05:04 UTC, ashish10677 commented
@Yashk767 code formatting is not done, build is failing, please format your code using `gofmt` and push.

2021-07-26 05:40 UTC, ashish10677 requested changes

2021-07-26 05:40 UTC, ashish10677 commented on cmd/stake.go
> +		return approvedStatus
This can be changed to `return utils.WaitForBlockCompletion(...)`

2021-07-26 05:40 UTC, ashish10677 commented on cmd/stake_test.go
> +	address := "0x53baCf1E1C6E14BB5700178Acf426dF6f0d5A949" // Provide your address for testing
Instead of hardcoding address, can't we generate address dynamically every time as we do in the `create` command?

2021-07-26 05:40 UTC, ashish10677 commented on cmd/stake_test.go
> +			name: "Test1: Staker is able to stake for the first time.",
What about tests for staking below minimum stake?

2021-07-26 06:22 UTC, Yashk767 commented on cmd/stake_test.go
> +	address := "0x53baCf1E1C6E14BB5700178Acf426dF6f0d5A949" // Provide your address for testing
If I generate the addresses dynamically in the same file, I also need to seed some SC's to the address which is generated just now.So I have to make that transfer work. I am working on it.

2021-07-26 06:38 UTC, Yashk767 commented on cmd/stake_test.go
> +			name: "Test1: Staker is able to stake for the first time.",
Yes, I will add it. Should I check the condition in the go function itself because that would be an instant check on running go function. If we are not checking that than by default it would check from bindings Stake function where it would return an revert error of Minimum stake when it hit the commit stake after time and run stake.

2021-07-26 06:51 UTC, ashish10677 commented on cmd/stake_test.go
> +			name: "Test1: Staker is able to stake for the first time.",
We need to check from go functions, not the bindings. The purpose of writing these tests are that our go functions are tested properly, bindings don't need to be tested.

2021-07-27 17:40 UTC, ashish10677 requested changes

2021-07-27 17:40 UTC, ashish10677 commented on cmd/stake_test.go
> +	balance, _ := utils.FetchBalance(client, address)
Why is the error not being caught over here?

2021-07-27 17:40 UTC, ashish10677 commented on cmd/stake_test.go
> +func getTransactionArgs1() types.TransactionOptions {
Please rename this function, `getTransactionArgs1` is not a good name at all.

2021-07-27 17:40 UTC, ashish10677 commented on cmd/stake_test.go
> +				newStakerID, _ := stakeManager.GetStakerId(&opts, common.HexToAddress(txnArgs.AccountAddress))
Add condition to check error here

2021-07-27 17:40 UTC, ashish10677 commented on cmd/stake_test.go
> +				staker, _ := utils.GetStaker(txnArgs.Client, txnArgs.AccountAddress, newStakerID)
Here as well

2021-07-30 09:31 UTC, SkandaBhat commented
How do I setup tests? This PR needs modifications in the readme as well. @Yashk767

2021-07-30 10:16 UTC, Yashk767 commented
> How do I setup tests? This PR needs modifications in the readme as well. @Yashk767

@SkandaBhat As we are trying to make the tests dynamic by generating the random addresses and seed them with faucets in the same file and than performing transactions with them but it is not being done yet. Currently we are asking the user to change the hard-coded address and replace it with its own. So I added setting up the testing environment in the PR info as of now, should we add it in readme after making it dynamic if its okay.

2021-08-12 08:14 UTC, SkandaBhat commented
Closing this as we are employing a different approach. cc: @ashish10677 @Yashk767

2021-08-12 08:14 UTC, closed without merging