Added valid ERC20 check for addresses
razor-network/razor-go pull request #873
Opened 2022-07-20 13:39 UTC by shyam-patel-kira

fixes #837

2022-07-21 09:10 UTC, ashish10677 requested changes

2022-07-21 09:10 UTC, ashish10677 commented on utils/common.go
> +func IsValidERC20Address(address string) {
@shyam-patel-kira please add tests for this function.
And it would be better if this function did not fatal here, rather it returned an error.
That error can be handled wherever this function is called.

2022-07-21 09:32 UTC, shyam-patel-kira commented on utils/common.go
> +func IsValidERC20Address(address string) {
okay

2022-07-21 13:07 UTC, shyam-patel-kira commented on utils/common.go
> +func IsValidERC20Address(address string) {
Done

2022-07-22 12:33 UTC, ashish10677 approved these changes

2022-07-22 12:33 UTC, merged