Added a warning for low ethBalance
razor-network/razor-go pull request #876
Opened 2022-07-21 11:59 UTC by Yashk767

# Description

Added a warning if ethBalance < 0.1
Fixes #840

2022-07-22 12:39 UTC, ashish10677 requested changes

2022-07-22 12:39 UTC, ashish10677 commented on cmd/vote.go
> +		log.Warn("Eth balance is lower than 0.1 ETH, kindly add more ETH to be safe for executing transactions successfully")
This should be SKL or SFuel balance, not Eth

2022-07-22 13:10 UTC, Yashk767 commented on cmd/vote.go
> +		log.Warn("Eth balance is lower than 0.1 ETH, kindly add more ETH to be safe for executing transactions successfully")
okay. I will replace `ETH` with `SKL`

2022-07-22 13:12 UTC, ashish10677 commented on cmd/vote.go
> +		log.Warn("Eth balance is lower than 0.1 ETH, kindly add more ETH to be safe for executing transactions successfully")
Replace it with sFUEL.

2022-07-25 10:23 UTC, ashish10677 commented on cmd/vote.go
> +		log.Warn("Eth balance is lower than 0.1 ETH, kindly add more ETH to be safe for executing transactions successfully")
@Yashk767 replace it with sFUEL

2022-07-25 12:16 UTC, merged