Fix : moved gasLimitMultiplier as constant in dispute.go
razor-network/razor-go pull request #883
Opened 2022-07-25 10:33 UTC by shekhar2807

# Description

- Moved gasLimitMultiplier as constant in dispute.go

Fixes #870

2022-07-26 13:33 UTC, ashish10677 requested changes

2022-07-26 13:33 UTC, ashish10677 commented on cmd/dispute.go
> +		var gasLimitMultiplier float32 = 5.5 //GasLimitMultiplier is used to increase the gas required from the gasLimit for the following function
Put this in constants.go

2022-07-26 18:58 UTC, ashish10677 requested changes

2022-07-26 18:58 UTC, ashish10677 commented on core/constants.go
> +var GasLimitMultiplier float32 = 5.5 //GasLimitMultiplier is used to increase the gas required from the gasLimit for the following function
Can you rename this to `DisputeGasMultiplier` and put the comment above the variable?

2022-07-27 04:54 UTC, shekhar2807 commented on core/constants.go
> +var GasLimitMultiplier float32 = 5.5 //GasLimitMultiplier is used to increase the gas required from the gasLimit for the following function
Done @ashish10677

2022-07-27 06:17 UTC, ashish10677 approved these changes

2022-07-27 06:17 UTC, merged