Add ETA to unlockWithdraw
razor-network/razor-go pull request #895
Opened 2022-07-27 10:30 UTC by shyam-patel-kira

fixes #885

2022-07-27 11:38 UTC, shekhar2807 requested changes

2022-07-27 11:38 UTC, shekhar2807 commented on cmd/unlockWithdraw.go
> +	txnArgs := types.TransactionOptions{
You can move txnArgs inside the below if. It would be more efficient.

2022-07-27 12:00 UTC, shyam-patel-kira commented on cmd/unlockWithdraw.go
> +	txnArgs := types.TransactionOptions{
Done. Thanks

2022-07-27 19:32 UTC, shekhar2807 approved these changes

2022-07-28 10:32 UTC, ashish10677 requested changes

2022-07-28 10:32 UTC, ashish10677 commented on cmd/initiateWithdraw.go
> +			log.Infof("Withdrawal Initiation period not reached. Cannot initiate withdraw now, please wait for %d epoch! (approximately %s)", waitFor, razorUtils.SecondsToReadableTime(int(timeRemaining)))
Remove this if else, keep one message.
`"Withdrawal Initiation period not reached. Cannot initiate withdraw now, please wait for %d epoch(s)! (approximately %s)`

2022-07-28 10:32 UTC, ashish10677 commented on cmd/unlockWithdraw.go
> +			log.Infof("Withdrawal period not reached. Cannot withdraw now, please wait for %d epoch! (approximately %s)", waitFor, razorUtils.SecondsToReadableTime(int(timeRemaining)))
Remove if else here as well.

2022-07-28 10:56 UTC, shyam-patel-kira commented on cmd/initiateWithdraw.go
> +			log.Infof("Withdrawal Initiation period not reached. Cannot initiate withdraw now, please wait for %d epoch! (approximately %s)", waitFor, razorUtils.SecondsToReadableTime(int(timeRemaining)))
Done

2022-07-28 10:56 UTC, shyam-patel-kira commented on cmd/unlockWithdraw.go
> +			log.Infof("Withdrawal period not reached. Cannot withdraw now, please wait for %d epoch! (approximately %s)", waitFor, razorUtils.SecondsToReadableTime(int(timeRemaining)))
Removed

2022-07-29 06:19 UTC, ashish10677 approved these changes

2022-07-29 06:19 UTC, merged