Fix: Move old features to the new main
razor-network/razor-go pull request #898
Opened 2022-07-29 18:57 UTC by shekhar2807

# Description

- GetIteration concurrency
- Moved chainId to config
- Added compress parameter in logger.go
- Godoc documentation for utils, logger, core, matrices

Fixes #860

2022-08-01 13:25 UTC, Yashk767 submitted a review, later dismissed
LGTM

2022-08-01 14:23 UTC, ashish10677 requested changes

2022-08-02 11:02 UTC, shekhar2807 commented on logger/logger.go
> +			Compress:   true,
Done @ashish10677

2022-08-02 11:10 UTC, ashish10677 commented on cmd/config-utils.go
> +		Compress:           "",
Is there any problem keeping this as a bool instead of a string?

2022-08-02 11:38 UTC, shekhar2807 commented on cmd/config-utils.go
> +		Compress:           "",
Yes, I tried using that also . It was throwing some errors . As far as String is concerned I checked for every possibility. It works for every case.

2022-08-02 11:41 UTC, shekhar2807 commented on cmd/config-utils.go
> +		Compress:           "",
Let me try that again, will update it here .

2022-08-02 12:14 UTC, shekhar2807 commented on cmd/config-utils.go
> +		Compress:           "",
if compress != "" {
 		viper.Set("compress", compress)
} . This if statement cause the issue if compress is stated as boolean . String solves this issue and make it easier to implement. @ashish10677

2022-08-03 11:08 UTC, ashish10677 approved these changes
Lgtm

2022-08-03 11:08 UTC, merged