Add Auto withdraw #867
razor-network/razor-go pull request #901
Opened 2022-08-04 08:57 UTC by shyam-patel-kira

fixes #867

2022-08-04 10:22 UTC, Yashk767 requested changes

2022-08-04 10:22 UTC, Yashk767 commented on cmd/initiateWithdraw.go
> +func (*UtilsStruct) AutoWithdraw(txnArgs types.TransactionOptions, stakerId uint32) error {
`AutoWithdraw` function is not being called anywhere except the tests. It should be called after the execution of initiateWithdraw transaction.

2022-08-04 11:23 UTC, Yashk767 requested changes

2022-08-04 11:23 UTC, Yashk767 commented on cmd/initiateWithdraw.go
> +	timeUtils.Sleep(time.Duration(core.EpochLength) * time.Second)
You need to wait for `withdrawLockPeriod`. It's not always 1, you need to set the sleep time according to that lockPeriod.

2022-08-05 12:43 UTC, shyam-patel-kira commented on cmd/initiateWithdraw.go
> +func (*UtilsStruct) AutoWithdraw(txnArgs types.TransactionOptions, stakerId uint32) error {
Fixed this

2022-08-05 12:43 UTC, shyam-patel-kira commented on cmd/initiateWithdraw.go
> +	timeUtils.Sleep(time.Duration(core.EpochLength) * time.Second)
resolved

2022-08-08 07:35 UTC, ashish10677 requested changes

2022-08-08 07:35 UTC, ashish10677 commented on cmd/initiateWithdraw.go
> +	txnOptions, err := cmdUtils.HandleUnstakeLock(client, types.Account{
Rather than returning txnOptions, can you not create txnOptions here and pass it to whichever function requires it? It'll be a little more consistent with the existing code.

2022-08-08 07:35 UTC, ashish10677 commented on cmd/initiateWithdraw.go
> +	timeUtils.Sleep(time.Duration(timeRemaining) * time.Second)
Can you put a log here, saying that waiting for lock to get over with the ETA?

2022-08-08 10:26 UTC, shyam-patel-kira commented on cmd/initiateWithdraw.go
> +	timeUtils.Sleep(time.Duration(timeRemaining) * time.Second)
Updated

2022-08-08 17:02 UTC, shyam-patel-kira commented on cmd/initiateWithdraw.go
> +	txnOptions, err := cmdUtils.HandleUnstakeLock(client, types.Account{
Update changes

2022-08-10 10:04 UTC, ashish10677 approved these changes

2022-08-18 12:34 UTC, Yashk767 approved these changes

2022-08-18 18:14 UTC, merged