Hotfix-giveSorted
razor-network/razor-go pull request #921
Opened 2022-09-05 09:35 UTC by Yashk767

# Description

- Reset Dispute is only after `FinalizeDispute`, removed from other dispute types.
- `ResetDispute` called irrespective of `FinalizeDispute` Txn status.

Fixes #911

2022-09-06 21:09 UTC, ashish10677 requested changes

2022-09-06 21:09 UTC, ashish10677 commented on cmd/dispute.go
> +	//Resetting dispute irrespective of FinalizeDispute transaction status
Are you sure we have to reset dispute irrespective of whether FinalizeDispute goes through or not?

2022-09-06 21:09 UTC, ashish10677 commented on cmd/dispute.go
> +			if (err1 == nil && err2 != nil) || (err1 != nil && err2 == nil) {
Shouldn't this be `if err1 != nil || err2 != nil`?
Even if we get one error, that means that we have to reset dispute right?

2022-09-07 06:27 UTC, Yashk767 commented on cmd/dispute.go
> +	//Resetting dispute irrespective of FinalizeDispute transaction status
Hmm yes, discussed with @SamAg19. 

After giveSorted, the state of dispute changes so irrespective of FinalizeDispute txn status, we need to reset the state for the next dispute. So that next giveSorted for other proposed block goes through.

2022-09-07 06:29 UTC, Yashk767 commented on cmd/dispute.go
> +			if (err1 == nil && err2 != nil) || (err1 != nil && err2 == nil) {
But if we get error in both i.e. `err1 != nil` &&` err2 != nil `, we dont need to reset dispute.

2022-09-07 08:44 UTC, ashish10677 approved these changes

2022-09-07 09:06 UTC, shekhar2807 approved these changes

2022-09-07 09:06 UTC, merged