Call claimStakerReward only if there reward to claim
razor-network/razor-go pull request #926
Opened 2022-09-05 13:53 UTC by shyam-patel-kira

fixes #908

2022-09-06 20:51 UTC, ashish10677 requested changes

2022-09-06 20:51 UTC, ashish10677 commented on cmd/claimCommission.go
> +	if stakerInfo.StakerReward.Cmp(big.NewInt(0)) == 1 {
Instead of `== 1` can you put it as `> 1`. Makes it easier to understand and is consistent with rest of the codebase

2022-09-07 08:03 UTC, shyam-patel-kira commented on cmd/claimCommission.go
> +	if stakerInfo.StakerReward.Cmp(big.NewInt(0)) == 1 {
> 1 would not be possible in any case
should I put it as > 0 ?

2022-09-07 08:42 UTC, shyam-patel-kira commented on cmd/claimCommission.go
> +	if stakerInfo.StakerReward.Cmp(big.NewInt(0)) == 1 {
done

2022-09-07 08:51 UTC, ashish10677 approved these changes

2022-09-07 08:55 UTC, Yashk767 approved these changes

2022-09-07 09:02 UTC, merged